# **NumPy**

**Introduction to NumPy**

NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra,fourier transform and matrices.
Understand the difference between one,two and n-dimensional array in NumPy.
Understand axis and shape properties for n-dimensional arrays.

**Installation of NumPy**

pip install numpy

In [ ]:
pip install numpy

Import NumPy

Once numpy is installed,import itin your applications by adding the import keyword.




In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


**NumPy Creating Arrays**

**Create a NumPy ndarray Object**

Numpy is used to work with arrays.The array object in NumPy is called ndarray.
We can create a NumPy ndarray object by using the array() function.

In [ ]:
import numpy as np
arr=np.array([1,3,5,7,9])
print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


**Dimensions in Arrays**

0-D,1-D,2-D,....,n-D array Dimensions can be created.


In [ ]:
import numpy as np
a=np.array(42) # 0-dimension
b=np.array([1,2,3,4,5]) # 1-dimension
c=np.array([[1,2,3],[4,5,6]]) # 2-dimension
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # 3-dimension

In [ ]:
print(a)
print(b)
print(c)
print(d)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


# Access Array Elements

Array indexing is the same as accessing an array element.
We can access an array element by referring to its index number.
The index of numpy starts with 0,it means first element has index 0 , second element has index 1 and so on.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
print(arr[2])

3


In [ ]:
arr=np.array([[23,45,5,32],[21,11,9,8]])
print(arr[1,1])

11


In [ ]:
arr=np.array([[[1,2,3,4],[45,67,54,1],[10,9,7,8]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3  4]
  [45 67 54  1]
  [10  9  7  8]]]
54


In [ ]:
arr=np.array([[[1,2,3],[5,6,7]],[[10,11,12],[14,15,16]]])
print(arr)
print(arr[1,1,2])

[[[ 1  2  3]
  [ 5  6  7]]

 [[10 11 12]
  [14 15 16]]]
16


# Slicing arrays
 Slicing in python means taking elements from one given index to another given index.
 [start:stop:step]


In [1]:
import numpy as np
arr=np.array([1,3,5,7,2,4])
print(arr[1:6])

[3 5 7 2 4]


In [2]:
print(arr[:-1])

[1 3 5 7 2]


In [3]:
print(arr[-2])

2


In [4]:
print(arr[1:6:2])

[3 7 4]


# 1-Dimension Array

In [5]:
import numpy as np
arr=np.array([1,3,5,7,9])
print(arr)

[1 3 5 7 9]


In [8]:
arr=np.random.randint(1,300,100)  # By using np.random.randint we can create random array by passing values.
print(arr)

[137 141 195 281 163 230  51  22 238 135 293 168 117  36 138 258 162 277
  88 252  30 258 132 236 184  64 177 207  67 190 277  32 206 286 147 186
  48 132 197 253 268 277 164 110 138  63 299 131 180 147 287  20 202  82
 277 261 140 158 218 244 101  53 192  33 148  58 204  37 209 132  96  78
  29 203 210 281  66 179 235  73 259 262 205 181 167 183 245 294  16 293
 251  16  90  21 172 172 216 124 253  58]


# 2-Dimensional Arrays

An array that has 1-D arrays as its element is called a 2-D array.This is also used to represent matrix.

In [10]:
import numpy as np
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
arr2.ndim  # ndim is used to identify the dimension of array.

[[1 2 3]
 [4 5 6]]


2

In [11]:
arr2=np.random.randint(1,200,(5,6))
print(arr2)

[[101  83 162 121  25  88]
 [141 177  67 186  96 177]
 [ 41 100 159 172 158  84]
 [138  10 192  63 140 154]
 [ 72  77 133   7  26  13]]


In [12]:
print(arr2[-1,-1])

13


In [13]:
print(arr2[0:5,0:3])

[[101  83 162]
 [141 177  67]
 [ 41 100 159]
 [138  10 192]
 [ 72  77 133]]


# 3-Dimension Arrays

An array that has 2-D arrays(matrices) as its elements is called 3-D array.

In [14]:
import numpy as np
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

arr3.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

In [15]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


REPLACING ONE ELEMENT WITH ANOTHER ONE

In [2]:
import numpy as np
arr3=np.random.randint(1,250,(4,10,6))
arr3

array([[[156,   5, 143, 249,   6, 234],
        [202, 130, 239, 235,  56,  96],
        [199,  12, 127, 249, 113, 147],
        [168, 242,  66,  58,  63, 240],
        [244,  79,  43, 160, 246, 126],
        [ 32,  55,   7, 104, 180, 145],
        [144, 120, 113, 233,  23, 220],
        [ 74,   1,  90,  86,  34,  31],
        [  3, 218, 178, 170, 192,  43],
        [ 98, 227,  14, 132, 150,  46]],

       [[ 23,  11, 239,  62,   5, 166],
        [102, 172, 127, 213, 136, 179],
        [ 19,  93, 208, 171,  63,  92],
        [ 33,  76,  25,  31, 179, 196],
        [146,  17, 143, 139, 114, 173],
        [202,   2,  79,  37,  38,  79],
        [ 21, 137, 131, 181,  65, 116],
        [235, 244, 186, 187,  86, 228],
        [ 23, 154, 119,  85, 234, 140],
        [112,  48,  78,  71,  50,  63]],

       [[ 98, 153,  91, 156, 175,  14],
        [ 86, 246, 179,  43, 241,  35],
        [ 64,  23, 150, 170,  20,   6],
        [244,  59, 158,  89, 110,  51],
        [232, 230,  78, 202, 182,  1

In [4]:
arr3[-1,-1,-1]=5880
arr3

array([[[ 156,    5,  143,  249,    6,  234],
        [ 202,  130,  239,  235,   56,   96],
        [ 199,   12,  127,  249,  113,  147],
        [ 168,  242,   66,   58,   63,  240],
        [ 244,   79,   43,  160,  246,  126],
        [  32,   55,    7,  104,  180,  145],
        [ 144,  120,  113,  233,   23,  220],
        [  74,    1,   90,   86,   34,   31],
        [   3,  218,  178,  170,  192,   43],
        [  98,  227,   14,  132,  150,   46]],

       [[  23,   11,  239,   62,    5,  166],
        [ 102,  172,  127,  213,  136,  179],
        [  19,   93,  208,  171,   63,   92],
        [  33,   76,   25,   31,  179,  196],
        [ 146,   17,  143,  139,  114,  173],
        [ 202,    2,   79,   37,   38,   79],
        [  21,  137,  131,  181,   65,  116],
        [ 235,  244,  186,  187,   86,  228],
        [  23,  154,  119,   85,  234,  140],
        [ 112,   48,   78,   71,   50,   63]],

       [[  98,  153,   91,  156,  175,   14],
        [  86,  246,  179,   4

In [8]:
arr3[-2,-1,-4]=8067
arr3

array([[[ 156,    5,  143,  249,    6,  234],
        [ 202,  130,  239,  235,   56,   96],
        [ 199,   12,  127,  249,  113,  147],
        [ 168,  242,   66,   58,   63,  240],
        [ 244,   79,   43,  160,  246,  126],
        [  32,   55,    7,  104,  180,  145],
        [ 144,  120,  113,  233,   23,  220],
        [  74,    1,   90,   86,   34,   31],
        [   3,  218,  178,  170,  192,   43],
        [  98,  227,   14,  132,  150,   46]],

       [[  23,   11,  239,   62,    5,  166],
        [ 102,  172,  127,  213,  136,  179],
        [  19,   93,  208,  171,   63,   92],
        [  33,   76,   25,   31,  179,  196],
        [ 146,   17,  143,  139,  114,  173],
        [ 202,    2,   79,   37,   38,   79],
        [  21,  137,  131,  181,   65,  116],
        [ 235,  244,  186,  187,   86,  228],
        [  23,  154,  119,   85,  234,  140],
        [ 112,   48,   78,   71,   50,   63]],

       [[  98,  153,   91,  156,  175,   14],
        [  86,  246,  179,   4

RESHAPING ARRAY ------------

In [9]:
np.arange(60)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [10]:
np.arange(60).reshape(20,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [11]:
arr45=np.arange(60).reshape(2,15,2)
arr45

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]])

In [12]:
arr45.ravel() #from nd to 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [13]:
arr45.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [16]:
arr=np.random.randint(1,200,(4,3))
arr

array([[122, 117,  11],
       [ 16, 167,  83],
       [156,  54,  72],
       [ 57,  31, 187]])

In [17]:
arr.shape

(4, 3)

MATH OPERATION -----------


In [20]:
import numpy as np
x=np.array([1,3,5,6,9])
x+10

array([11, 13, 15, 16, 19])

In [21]:
x-10

array([-9, -7, -5, -4, -1])

In [22]:
x*10

array([10, 30, 50, 60, 90])

In [23]:
x/10

array([0.1, 0.3, 0.5, 0.6, 0.9])

In [24]:
np.square(x)

array([ 1,  9, 25, 36, 81])

In [27]:
x=np.array([13,65,5])
z=np.array([2,5,40])
np.add(x,z) #Adding opertion of 2 d array

array([15, 70, 45])

In [26]:
np.subtract(x,z) #substract opertion of 2 d array

array([ 11,  60, -35])

In [28]:
np.multiply(x,z)

array([ 26, 325, 200])

In [29]:
np.divide(x,z)

array([ 6.5  , 13.   ,  0.125])

SUMMARY OPERATION ----------------------


In [30]:
import numpy as np
arr=np.random.randint(1,300,(4,2))
arr

array([[ 73,  65],
       [ 32,  37],
       [231,  85],
       [ 41, 133]])

In [31]:
arr.shape # calculate number of rows and column

(4, 2)

In [32]:
np.transpose(arr).shape

(2, 4)

In [33]:
arr123=arr.ravel()
arr123

array([ 73,  65,  32,  37, 231,  85,  41, 133])

In [34]:
arr123.max() # for max value

231

In [35]:
arr123.min()# for min value

32

In [36]:
arr123.mean()# for mean value

87.125

In [37]:
np.median(arr123) # for median

69.0

In [38]:
arr.argmin() # for min position

2

In [39]:
arr.argmax()   # for max position

4

In [40]:
arr.sort() # sorting in ascending order
arr

array([[ 65,  73],
       [ 32,  37],
       [ 85, 231],
       [ 41, 133]])

In [41]:
arr[::-1] #for reverse order sorting

array([[ 41, 133],
       [ 85, 231],
       [ 32,  37],
       [ 65,  73]])

In [42]:
arr.argsort()# sort acc to indexing

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1]], dtype=int64)

In [43]:
arr.shape

(4, 2)